vich_uploader:
    db_driver: orm

    mappings:
        meal_images:
            uri_prefix:         '%app.path.meal_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.meal_images%'
